# Generated by Django 2.0.13 on 2019-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
